"""Wire-protocol Python types for every batchalign worker boundary.

This module is the **stable public name** that backends import from. It
re-exports every generated pydantic-v2 type from the sibling
`_proto_generated` module (autogenerated from the Rust schemars output via
the Bazel `_proto_generated` genrule) and contributes the hand-written
rehydration helpers that bridge Rust serde's tagged-enum JSON to typed
Python instances.

Source of truth: `crates/batchalign/batchalign-core/src/proto/*.rs` plus
the `TaskInput` / `TaskOutput` unions in `base.rs`. To change a field,
edit the Rust file and rebuild — the next `bazel build` regenerates the
Python side. There is no `just gen-proto` recipe and no manual codegen
step; if `_proto_generated.py` is missing, the Bazel py_library wiring is
broken (or you ran `maturin develop` without the Bazel-staged copy).

Why a shim and not regenerate-into-this-file: the rehydration helpers
(`rebuild_tagged_inputs`, `serialize_tagged_outputs`) are called by the
Rust-side `BackendImpl::call` over JSON and need to live somewhere the
generator never overwrites.
"""

from __future__ import annotations

from typing import Any

# Re-export every generated type. The generated module is the single
# canonical source for the class set; `__all__` is computed from its
# public names so adding/removing a Rust proto type propagates here
# automatically on the next Bazel build.
from batchalign._core._proto_generated import (  # noqa: F401
    # AI
    AiInput,
    AiOutput,
    AiRevision,
    AiUtterance,
    # Shared
    LanguageSpecAuto,
    LanguageSpecCode,
    LanguageSpecPerFile,
    PreparedAudio,
    # ASR
    AsrInput,
    AsrOptions,
    AsrOutput,
    AsrSegment,
    AsrWord,
    # Forced alignment
    FaInput,
    FaOutput,
    # Phonetic transcription
    PhoneticInput,
    PhoneticOutput,
    PhoneticUtterance,
    PhoneticUnit,
    PhoneticResult,
    # Speaker diarization
    Diarization,
    DiarizationSegment,
    SpeakerInput,
    SpeakerOutput,
    # Utterance segmentation
    UtSegInput,
    UtSegOutput,
    UtteranceSpan,
    # Morphosyntax
    GraTerminator,
    MorphosyntaxInput,
    MorphosyntaxOutput,
    MorphosyntaxToken,
    MorphosyntaxUnit,
    MorphosyntaxUtterance,
    # Translate
    TranslateInput,
    TranslateOutput,
    # Coref
    CorefInput,
    CorefOutput,
    # Compare
    CompareInput,
    CompareMetrics,
    CompareMetricsPos,
    CompareOutput,
    # Convert
    ConvertInput,
    MediaFormat,
    MediaOutput,
    # Tagged unions
    TaskInput,
    TaskOutput,
    # Per-variant union members (TaskInputAsr, TaskOutputAsr, …) are
    # available on `_proto_generated` for advanced uses but not normally
    # imported here — backends only need the input/output classes.
)

# `LanguageSpec` is the discriminated-union alias most backends want. The
# generated module emits one BaseModel per variant; expose a tuple alias so
# `isinstance(spec, LanguageSpec)` works ergonomically.
LanguageSpec = (LanguageSpecAuto, LanguageSpecCode, LanguageSpecPerFile)


# ---------------------------------------------------------------------------
# Tagged-dict → typed pydantic rehydration.
#
# The Rust engine ships a serde-JSON encoding of `Vec<TaskInput>` (each item
# tagged `{"task": "<Variant>", "data": {...}}`) across the PyO3 boundary;
# we reconstitute each item to its typed proto class here so backend
# `call()` methods see a real `MorphosyntaxInput` (with a real
# `LanguageSpecAuto` nested) instead of plain dicts. The inverse helper
# serializes a backend's typed `*Output` instances back to that same
# tagged-dict shape for the round-trip.
# ---------------------------------------------------------------------------

# Tag → input dataclass. Tag values are the Rust enum variant names from
# `crates/batchalign/batchalign-core/src/base.rs::TaskInput` and must stay
# in lockstep with serde's `#[serde(tag = "task", content = "data")]`
# encoding. The generated `TaskInput` discriminated union enforces the same
# mapping; this table exists separately because `rebuild_tagged_inputs`
# receives one item at a time, not a wrapped list.
_TAG_TO_INPUT: dict[str, type] = {
    "Ai": AiInput,
    "Asr": AsrInput,
    "Fa": FaInput,
    "Phonetic": PhoneticInput,
    "Speaker": SpeakerInput,
    "UtSeg": UtSegInput,
    # UTR's wire payload is byte-identical to AsrInput (Rust-side
    # `UtrInput` is a serde-transparent newtype over `AsrInput`), so we
    # rehydrate it into the same Python dataclass. Any ASR backend that
    # has opted into the `UTR` marker handles the resulting `AsrInput`
    # unchanged.
    "Utr": AsrInput,
    "Morphosyntax": MorphosyntaxInput,
    "Translate": TranslateInput,
    "Coref": CorefInput,
    "Compare": CompareInput,
    "Convert": ConvertInput,
}

_OUTPUT_TO_TAG: dict[type, str] = {
    AiOutput: "Ai",
    AsrOutput: "Asr",
    FaOutput: "Fa",
    PhoneticOutput: "Phonetic",
    SpeakerOutput: "Speaker",
    UtSegOutput: "UtSeg",
    MorphosyntaxOutput: "Morphosyntax",
    TranslateOutput: "Translate",
    CorefOutput: "Coref",
    CompareOutput: "Compare",
    MediaOutput: "Convert",
}


def rebuild_tagged_inputs(items: list[dict]) -> list[Any]:
    """Convert a list of `{"task": tag, "data": {...}}` dicts (as produced
    by Rust serde's `TaskInput` tagged-enum serialisation) into typed proto
    pydantic instances ready to feed a Python `Backend.call()`."""
    out: list[Any] = []
    for item in items:
        tag = item.get("task")
        cls = _TAG_TO_INPUT.get(tag)
        if cls is None:
            raise TypeError(f"unknown TaskInput tag {tag!r}")
        out.append(cls.model_validate(item.get("data", {})))
    return out


def serialize_tagged_outputs(
    items: list[Any], input_tags: list[str] | None = None
) -> list[dict]:
    """Inverse of `rebuild_tagged_inputs`: take a list of typed `*Output`
    pydantic instances and emit the tagged-dict shape Rust serde expects.

    When `input_tags` is provided (one per item, in the same order as the
    inputs that produced them), the output tag is taken from there
    instead of looked up by Python type. This is how `AsrOutput` returned
    from a `Task.Utr` dispatch gets serialized back as `{"task": "Utr"}`
    rather than `{"task": "Asr"}` — UTR's wire payload is identical to
    ASR's, so type alone can't disambiguate.

    `model_dump(mode='json')` matches what `serde_json` parses on the
    Rust side — bytes round-trip as base64 strings, etc.
    """
    out: list[dict] = []
    for i, item in enumerate(items):
        if input_tags is not None and i < len(input_tags):
            tag: str | None = input_tags[i]
        else:
            tag = _OUTPUT_TO_TAG.get(type(item))
        if tag is None:
            raise TypeError(f"unknown Output type {type(item).__name__}")
        out.append({"task": tag, "data": item.model_dump(mode="json")})
    return out
